### ISSUE TITLE
Not enough credit to the original author

### ISSUE THREAD

**Issue by elken** [Anoncheg1/dired-hist#1]
There's been some bad-faith development practice here, and I would advise you in future to not engage in development this way.

As you are aware, this is not all code you've written; this is a fork of another package of the same name. Instead of using the correct process for forking a project, you instead did [this](https://github.com/Anoncheg1/dired-hist/commit/70dd535b69075dd4af809e475b9be0d4fba718d6) and have made some minor changes since. You've also pushed this to MELPA without any credit to Karthik.

You've filled in the author field wrong to add yourself as a secondary author, thus confusing things further. I would suggest renaming the package and adding proper credit to Karthik.

Of course you're not mandated to abide any of this, but continuing to follow this practice will have you shunned from the wider communities.

**Comment by Anoncheg1** [comment]
I changed order of Authors in dired-hist.el and added link in README.
